intel + arm macs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,44 +36,46 @@ jobs:
 
       - name: Run tests
         # We need to build first to ensure the dynamic library is created
-        run: cargo build && cargo test
+        run: cargo build --features videotoolbox && cargo test --features videotoolbox
+
       - name: Build release
         # On macOS, we need to build with the videotoolbox feature to get hardware acceleration
         run: cargo build --release --features videotoolbox
 
-  #   build-macos-arm:
-  #     runs-on: macos-latest
+  build-macos-arm:
+    runs-on: macos-latest
 
-  #     steps:
-  #       - uses: actions/checkout@v2
+    steps:
+      - uses: actions/checkout@v2
 
-  #       - name: Set up Rust
-  #         uses: actions-rs/toolchain@v1
-  #         with:
-  #           profile: minimal
-  #           toolchain: stable
-  #           override: true
+      - name: Set up Rust
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
 
-  #       - name: Create data directory
-  #         run: mkdir -p data
+      - name: Create data directory
+        run: mkdir -p data
 
-  #       - name: Download test video
-  #         run: curl -L -o data/test.mp4 https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
+      - name: Download test video
+        run: curl -L -o data/test.mp4 https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
 
-  #       - name: Verify download
-  #         run: |
-  #           if [ ! -f data/test.mp4 ]; then
-  #             echo "Failed to download test video"
-  #             exit 1
-  #           fi
-  #           echo "Test video downloaded successfully"
+      - name: Verify download
+        run: |
+          if [ ! -f data/test.mp4 ]; then
+            echo "Failed to download test video"
+            exit 1
+          fi
+          echo "Test video downloaded successfully"
 
-  #       - name: Run tests
-  #         # We need to build first to ensure the dynamic library is created
-  #         run: cargo build && cargo test
-  #       - name: Build release
-  #         # On macOS, we need to build with the videotoolbox feature to get hardware acceleration
-  #         run: cargo build --release --features videotoolbox
+      - name: Run tests
+        # We need to build first to ensure the dynamic library is created
+        run: cargo build --features videotoolbox && cargo test --features videotoolbox
+
+      - name: Build release
+        # On macOS, we need to build with the videotoolbox feature to get hardware acceleration
+        run: cargo build --release --features videotoolbox
 
   build-windows:
     runs-on: windows-latest
@@ -110,13 +112,14 @@ jobs:
             exit 1
           }
           Write-Output "Test video downloaded successfully"
+
       - name: Run tests
         shell: msys2 {0}
         env:
           MSYSTEM: MINGW64
         run: |
           which sh
-          cargo build --verbose && cargo test --verbose
+          cargo build --verbose --features d3d12va && cargo test --features d3d12va --verbose
 
       - name: Build release
         shell: msys2 {0}
